server {
    listen 666 ssl;
    server_name streams.upg.gr;

    ssl_certificate     /etc/letsencrypt/live/streams.upg.gr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/streams.upg.gr/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    client_max_body_size 10m;

    location /api/ {
        proxy_pass http://api:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /hls/ {
        proxy_pass http://hls-nginx:8080/hls/;
        add_header Cache-Control "no-cache";
        add_header Access-Control-Allow-Origin "*";
        add_header Access-Control-Allow-Headers "*";
    }

    location /dash/ {
        proxy_pass http://hls-nginx:8080/dash/;
        add_header Cache-Control "no-cache";
        add_header Access-Control-Allow-Origin "*";
        add_header Access-Control-Allow-Headers "*";
    }

    location /watch/ {
        proxy_pass http://api:3000;
    }

    location / {
        proxy_pass http://api:3000;
        proxy_set_header Host $host;
    }
}
